// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2pxtnKBvviPiTshD2Bla4j7LMVUbKcWY',
    appId: '1:627000862412:web:6a33c327f62e8b8bedc469',
    messagingSenderId: '627000862412',
    projectId: 'chatapp-a7dfd',
    authDomain: 'chatapp-a7dfd.firebaseapp.com',
    databaseURL: 'https://chatapp-a7dfd-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7dfd.appspot.com',
    measurementId: 'G-13LEB9YJV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmz3bZGO4_HHcvmgVZDrkT7DK43pn9FFE',
    appId: '1:627000862412:android:aee14e89216e9311edc469',
    messagingSenderId: '627000862412',
    projectId: 'chatapp-a7dfd',
    databaseURL: 'https://chatapp-a7dfd-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7dfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCduTZ_ikfNG4Ib7vhuDCs9p3OWpNIepCE',
    appId: '1:627000862412:ios:e20ff284041c9cb4edc469',
    messagingSenderId: '627000862412',
    projectId: 'chatapp-a7dfd',
    databaseURL: 'https://chatapp-a7dfd-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7dfd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCduTZ_ikfNG4Ib7vhuDCs9p3OWpNIepCE',
    appId: '1:627000862412:ios:e20ff284041c9cb4edc469',
    messagingSenderId: '627000862412',
    projectId: 'chatapp-a7dfd',
    databaseURL: 'https://chatapp-a7dfd-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7dfd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2pxtnKBvviPiTshD2Bla4j7LMVUbKcWY',
    appId: '1:627000862412:web:a22c92038165316eedc469',
    messagingSenderId: '627000862412',
    projectId: 'chatapp-a7dfd',
    authDomain: 'chatapp-a7dfd.firebaseapp.com',
    databaseURL: 'https://chatapp-a7dfd-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-a7dfd.appspot.com',
    measurementId: 'G-P6SVFF9256',
  );
}
